# Generated by Django 4.1.7 on 2023-03-08 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBLRuleFunctionsOperation',
            fields=[
                ('functions_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('functions_name', models.CharField(blank=True, max_length=200, null=True)),
                ('isOpertion', models.BooleanField(blank=True, default=False, null=True)),
                ('isFuntion', models.BooleanField(blank=True, default=False, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_rules_functions_operation',
            },
        ),
        migrations.CreateModel(
            name='TBLRules',
            fields=[
                ('rules_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('rules_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rules_sequence', models.IntegerField(blank=True, null=True)),
                ('isOpty', models.BooleanField(blank=True, default=False, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_rules',
            },
        ),
        migrations.CreateModel(
            name='TBLRulesConfiguration',
            fields=[
                ('rules_config_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('rules_config_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rules_set_sequence', models.IntegerField(blank=True, null=True)),
                ('condition_sequence', models.IntegerField(blank=True, null=True)),
                ('isUiVisible', models.BooleanField(blank=True, default=False, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('function_id', models.ForeignKey(db_column='function_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrulefunctionsoperation')),
                ('rules_id', models.ForeignKey(db_column='rules_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrules')),
            ],
            options={
                'db_table': 'tbl_rules_configuration',
            },
        ),
        migrations.CreateModel(
            name='TBLRulesConfigurationCondition',
            fields=[
                ('rcc_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('isLhs', models.BooleanField(blank=True, default=False, null=True)),
                ('rcc_sequence', models.IntegerField(blank=True, null=True)),
                ('rcc_type', models.IntegerField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('function_id', models.ForeignKey(db_column='function_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrulefunctionsoperation')),
                ('operation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_id', to='rule_engine.tblrulefunctionsoperation')),
                ('rules_config_id', models.ForeignKey(db_column='rules_config_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrulesconfiguration')),
            ],
            options={
                'db_table': 'tbl_rules_configuration_condition',
            },
        ),
        migrations.CreateModel(
            name='TBLRulesSet',
            fields=[
                ('rules_set_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('rules_set_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rules_set_sequence', models.IntegerField(blank=True, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rules_id', models.ForeignKey(db_column='rules_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrules')),
            ],
            options={
                'db_table': 'tbl_rules_set',
            },
        ),
        migrations.CreateModel(
            name='TBLRulesGroup',
            fields=[
                ('rules_group_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('parent_group_no', models.IntegerField(blank=True, null=True)),
                ('group_no', models.IntegerField(blank=True, null=True)),
                ('rule_set_condition', models.CharField(blank=True, max_length=200, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rules_config_id', models.ForeignKey(db_column='rules_config_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrulesconfiguration')),
            ],
            options={
                'db_table': 'tbl_rules_group',
            },
        ),
        migrations.CreateModel(
            name='TBLRulesConfigurationValues',
            fields=[
                ('rcv_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('rcv_sequence', models.IntegerField(blank=True, null=True)),
                ('value_type', models.IntegerField(blank=True, null=True)),
                ('value_display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('value_tooltip', models.CharField(blank=True, max_length=200, null=True)),
                ('value_table_name', models.CharField(blank=True, max_length=200, null=True)),
                ('value_table_column', models.CharField(blank=True, max_length=200, null=True)),
                ('value_name', models.CharField(blank=True, max_length=200, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rcc_id', models.ForeignKey(db_column='rcc_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrulesconfigurationcondition')),
            ],
            options={
                'db_table': 'tbl_rules_configuration_values',
            },
        ),
        migrations.CreateModel(
            name='TBLRulesAudit',
            fields=[
                ('rules_audit_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, max_length=200, null=True)),
                ('old_value', models.CharField(blank=True, max_length=200, null=True)),
                ('new_value', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rules_config_id', models.ForeignKey(db_column='rules_config_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrulesconfiguration')),
                ('rules_group_id', models.ForeignKey(db_column='rules_group_id', on_delete=django.db.models.deletion.CASCADE, to='rule_engine.tblrulesgroup')),
            ],
            options={
                'db_table': 'tbl_rules_audit',
            },
        ),
    ]
