# Generated by Django 4.1.7 on 2023-03-16 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMaster',
            fields=[
                ('cm_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('cm_type', models.CharField(blank=True, max_length=200, null=True)),
                ('cm_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cm_value', models.CharField(blank=True, max_length=200, null=True)),
                ('extras', models.JSONField(blank=True, default=dict, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('isActive', models.BooleanField(blank=True, default=False, null=True)),
                ('created_user', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_user', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_common_master',
            },
        ),
    ]
