# Generated by Django 4.1.7 on 2023-03-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule_engine', '0002_commonmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmaster',
            name='cm_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
